Merged PR 1288999: Downgrade python attrs in CI to unblock automated tests
Downgrade python attrs module in CI because of
TypeError: attrib() got an unexpected keyword argument 'convert'
when running python unit tests with attrs 19.2.0 released today.

Alternative would be to use newer pytest, but compatibility has not been verified.

Related work items: #2072952